language: python
dist: trusty
env:
    global:
        - TOXENV=py27
        - DOCKER_USER=travisrw@us.ibm.com
        - DOCKER_IMAGE_HOST=txo-whitewater-public-docker-local.artifactory.swg-devops.com
        - DOCKER_IMAGE=txo-whitewater-public-docker-local.artifactory.swg-devops.com/whitewater-detect-secrets
        - DOCKER_IMAGE_TAG="$TRAVIS_BUILD_NUMBER-id-$TRAVIS_BUILD_ID-time-$(date +%s)"
        - DOCKER_IMAGE_TAG_DSS="$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER-id-$TRAVIS_BUILD_ID-time-$(date +%s)"
deploy:
- provider: script
  script: docker login $DOCKER_IMAGE_HOST --username $DOCKER_USER --password $DOCKER_PASS
    && docker push $DOCKER_IMAGE:$DOCKER_IMAGE_TAG
    && docker tag $DOCKER_IMAGE:$DOCKER_IMAGE_TAG $DOCKER_IMAGE:latest
    && docker push $DOCKER_IMAGE:latest
  on:
    branch: master
- provider: script
  script: docker login $DOCKER_IMAGE_HOST --username $DOCKER_USER --password $DOCKER_PASS
    && docker tag $DOCKER_IMAGE:$DOCKER_IMAGE_TAG $DOCKER_IMAGE:$DOCKER_IMAGE_TAG_DSS
    && docker push $DOCKER_IMAGE:$DOCKER_IMAGE_TAG_DSS
    && docker tag $DOCKER_IMAGE:$DOCKER_IMAGE_TAG_DSS $DOCKER_IMAGE:dss-latest
    && docker push $DOCKER_IMAGE:dss-latest
  on:
    branch: dss
matrix:
    include:
        - env: TOXENV=py27
          python: 2.7
        - env: TOXENV=py35
          python: 3.5
        - env: TOXENV=py36
          python: 3.6
        - env: TOXENV=py37
          python: 3.7
          dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
        # - env: TOXENV=pypy
        #   python: pypy
install:
    - pip install tox
script: make test && docker build -t $DOCKER_IMAGE:$DOCKER_IMAGE_TAG --no-cache .
cache:
    directories:
        - $HOME/.cache/pre-commit
services:
    - docker
