language: python

git:
  depth: false
services:
    - docker
deploy:
- provider: script
  script: >-
        set -e; make docker-build-images docker-test-images setup-trivy docker-quality-images deploy
  on:
    all_branches: true
    # only build docker image and push once
    condition: $TOXENV = py38
    # only deploy when pushing to ghe repo
    repo: Whitewater/whitewater-detect-secrets

matrix:
    include:
        - env: TOXENV=py27
          python: 2.7
        - env: TOXENV=py35
          python: 3.5
        - env: TOXENV=py36
          python: 3.6
        - env: TOXENV=py37
          python: 3.7
          dist: xenial  # Required for Python >= 3.7 (travis-ci/travis-ci#9069)
        - env: TOXENV=py38
          python: 3.8
          dist: xenial  # Required for Python >= 3.7 (travis-ci/travis-ci#9069)
        # - env: TOXENV=pypy
        #   python: pypy
install:
    - pip install tox
script: make test
cache:
    directories:
        - $HOME/.cache/pre-commit
        - $HOME/.cache/trivy
