language: python
dist: trusty
env:
    global:
        - TOXENV=py27
        - DOCKER_REGISTRY=us.icr.io
        - DOCKER_USER=iamapikey
        - DOCKER_IMAGES="dsl detect-secrets detect-secrets-hook"
        - DOCKER_LOCAL_DOMAIN=git-defenders
        - DOCKER_REMOTE_DOMAIN=us.icr.io/git-defenders
        - DOCKER_IMAGE_TAG="$TRAVIS_BUILD_NUMBER-id-$TRAVIS_BUILD_ID-time-$(date +%s)"
        - DOCKER_IMAGE_TAG_DSS="$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER-id-$TRAVIS_BUILD_ID-time-$(date +%s)"
deploy:
- provider: script
  script: |
        echo ${IBM_CLOUD_API_KEY} | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY

        for image_name in $DOCKER_IMAGES
        do
          ./tag-and-publish.sh $DOCKER_LOCAL_DOMAIN/$image_name $DOCKER_REMOTE_DOMAIN/$image_name:$DOCKER_IMAGE_TAG
          ./tag-and-publish.sh $DOCKER_LOCAL_DOMAIN/$image_name $DOCKER_REMOTE_DOMAIN/$image_name:latest
        done
  on:
      branch: master
- provider: script
  script: |
        echo ${IBM_CLOUD_API_KEY} | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY

        for image_name in $DOCKER_IMAGES
        do
          ./tag-and-publish.sh $DOCKER_LOCAL_DOMAIN/$image_name $DOCKER_REMOTE_DOMAIN/$image_name:$DOCKER_IMAGE_TAG_DSS
          ./tag-and-publish.sh $DOCKER_LOCAL_DOMAIN/$image_name $DOCKER_REMOTE_DOMAIN/$image_name:dss-latest
        done
  on:
      branch: dss
matrix:
    include:
        - env: TOXENV=py27
          python: 2.7
        - env: TOXENV=py35
          python: 3.5
        - env: TOXENV=py36
          python: 3.6
        - env: TOXENV=py37
          python: 3.7
          dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
        # - env: TOXENV=pypy
        #   python: pypy
install:
    - pip install tox
script: |
      make test
      ./build-dockerfiles.sh

      # Publish image and labled with tag when a git tag is pushed
      if [ -n "$TRAVIS_TAG" ]; then
        echo ${IBM_CLOUD_API_KEY} | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
        for image_name in $DOCKER_IMAGES
        do
          ./tag-and-publish.sh $DOCKER_LOCAL_DOMAIN/$image_name $DOCKER_REMOTE_DOMAIN/$image_name:$TRAVIS_TAG
        done
      fi
cache:
    directories:
        - $HOME/.cache/pre-commit
services:
    - docker
